### ISSUE TITLE
Compatibility with Magento 2.4 / PHP 7.4

### ISSUE THREAD

**Issue by in-session** [netresearch/dhl-module-carrier-paket#1]
Hi,

there is already an info when the modules support PHP 7.4.

```
  Problem 1
    - dhl/module-carrier-paket 1.1.0 requires php ~7.0.6 || ~7.1.3 || ~7.2.0 || ~7.3.0 -> your PHP version (7.4.7) does not satisfy that requirement.
    - dhl/module-carrier-paket 1.1.0 requires php ~7.0.6 || ~7.1.3 || ~7.2.0 || ~7.3.0 -> your PHP version (7.4.7) does not satisfy that requirement.
    - Installation request for dhl/module-carrier-paket 1.1.0 -> satisfiable by dhl/module-carrier-paket[1.1.0].
```

**Comment by powli** [comment]
Hi @in-session,

the module will always support the PHP versions that are supported by the Magento versions it is compatible with. At the moment that means Magento 2.2 and 2.3.
We are currently hard at work to provide compatibility with 2.4 (which will also support PHP 7.4) and will release a compatible version as soon as possible.

**Comment by MarcusWolschon** [comment]
Why is this closed when there is no new release (thus the issue is not fixed)
https://github.com/netresearch/dhl-module-carrier-paket/releases
and no new release of dhl-shipping-m2 referencing that new release?
https://github.com/netresearch/dhl-shipping-m2/releases

**Comment by mam08ixo** [comment]
This issue is not closed.

**Comment by MarcusWolschon** [comment]
Sorry, my mistake. The red badge "closed" above is for the linked issue. Not an updated status of this one.

**Comment by ngolatka** [comment]
Please see https://github.com/netresearch/dhl-shipping-m2/releases

Version 1.2.0 of the dhl-shipping-m2 metapackage includes compatibility with M 2.4.
