### ISSUE TITLE
PHP 8.1

### ISSUE THREAD

**Issue by YiffyToys** [netresearch/dhl-module-carrier-paket#10]
The README.md states "PHP >= 7.1.3"
but the composer.json says `php": "^7.1.3"`
it also depends on "dhl/sdk-api-parcel-management" that us not yet PHP 8.1 compatible.

So it is not compatible with Magento 2.4.5 or 2.4.4 and only usable up to 2.4.3-p2.
https://devdocs.magento.com/guides/v2.4/install-gde/system-requirements.html

**Comment by mam08ixo** [comment]
We are well aware that the module is not compatible with the 2.4.4 system requirements, thanks.

Follow https://github.com/netresearch/dhl-shipping-m2/issues/44 for updates.
