### ISSUE TITLE
Street containing slash parsed wrongly

### ISSUE THREAD

**Issue by HenKun** [netresearch/dhl-module-carrier-paket#2]
## Description

A street containnig a slash is parsed wrongly by the DHL module, resulting in a wrong (but valid) address send to DHL, resulting in a failed delivery. There are two slightly different cases.

## Preconditons

- Magento 2.4.1
- DHL  `dhl/shipping-m2` 1.5.1

# Case 1

## Steps to reproduce

- Create an order with address 'Kollmitz 1 1/3, 93466 Chamerau' 

## Expected Behavior

- The address is split in:
- Street: 'Kollmitz'
- Housenumber: '1 1/3'
- Addition: ''
- OR:
- Street: 'Kollmitz'
- Housenumber: '1'
- Addition: '1/3'
- The shipping label contains the correct street, housenumber and addition 'Kollmitz 1 1/3'

## Actual Behavior

- The address is split in:
- Street: 'Kollmitz'
- Housenumber: '11'
- Addition: '3'
- The shipping label contains 'Kollmitz 11' 
- --> false number and even the addition is not added (which would be wrong anyway)
![Kollmitz](https://user-images.githubusercontent.com/18382633/111772720-7c3ca100-88ad-11eb-8ec4-cc0d5fca1e0e.png)

# Case 2

## Steps to reproduce

- Create an order with address 'Hauptstraße 4/1, 73557 Mutlangen' 

## Expected Behavior

- The address is split in:
- Street: 'Hauptstraße'
- Housenumber: '4/1'
- Addition: ''
- OR:
- Street: 'Kollmitz'
- Housenumber: '4'
- Addition: '1'
- The shipping label contains the correct street, housenumber and addition 'Hauptstraße 4/1'

## Actual Behavior

- The address is split in:
- Street: 'Hauptstraße'
- Housenumber: '4'
- Addition: '1'
- The shipping label contains 'Hauptstraße 4' 
- --> This is not an issue of wrong parsing, but of not adding the addition to the label
- ![Hauptstrasse](https://user-images.githubusercontent.com/18382633/111772744-82cb1880-88ad-11eb-839b-3e1774c45018.png)

# Disclaimer

We already had a discussion in another issue about the complexity of address parsing, so I know this can be a highly difficult issue. Just as a remark, these are two examples of existing german addresses, but admittetly rather rare. In Austria it is way more common that the housenumber contains a slash.

**Comment by mam08ixo** [comment]
[DHL Shipping version 2.0.0](https://github.com/netresearch/dhl-shipping-m2/releases/tag/2.0.0) allows to apply post-processing rules to the street splitter. As discussed, we added such a rule for addresses in Baden-Württemberg.

https://github.com/netresearch/dhl-module-carrier-paket/blob/cbe674ec1950b68f633b86a61640baba5819bcc8/etc/di.xml#L99-L100

The rule moves the `/1` back from the supplement to the street number in addresses like "Hauptstraße 4/1". If you like to apply the rule to all addresses in Germany (or do not require region information in your store), you can simply add the same rule via DI configuration with only the country code as item name (compare the Italy rule).
