### ISSUE TITLE
Magento 2.4.3: Zend\Hydrator\Reflection incompatibility

### ISSUE THREAD

**Issue by phoenix-bjoern** [netresearch/dhl-module-carrier-paket#3]
Magento 2.4.3 uses `Laminas\Hydrator` which deprecates the usage of `Laminas\Hydrator\Reflection`.
Since `Model/Pipeline/CreateShipments/ShipmentRequest/RequestExtractor.php` uses `Zend\Hydrator\Reflection` this causes an error (see https://github.com/laminas/laminas-hydrator/blob/4.3.x/src/Reflection.php#L13).
Instead it should use `Laminas\Hydrator\ReflectionHydrator` as stated in the error message.

**Comment by phoenix-bjoern** [comment]
You can use the following patch for Magento 2.4.3:
```
diff --git a/vendor/dhl/module-carrier-paket/Model/Pipeline/CreateShipments/ShipmentRequest/RequestExtractor.php b/vendor/dhl/module-carrier-paket/Model/Pipeline/CreateShipments/ShipmentRequest/RequestExtractor.php
index ea8af5828c..34608db2bd 100644
--- a/vendor/dhl/module-carrier-paket/Model/Pipeline/CreateShipments/ShipmentRequest/RequestExtractor.php
+++ b/vendor/dhl/module-carrier-paket/Model/Pipeline/CreateShipments/ShipmentRequest/RequestExtractor.php
@@ -26,7 +26,7 @@ use Netresearch\ShippingCore\Api\Pipeline\ShipmentRequest\RequestExtractor\Servi
 use Netresearch\ShippingCore\Api\Pipeline\ShipmentRequest\RequestExtractor\ServiceOptionReaderInterfaceFactory;
 use Netresearch\ShippingCore\Api\Pipeline\ShipmentRequest\RequestExtractorInterface;
 use Netresearch\ShippingCore\Api\Pipeline\ShipmentRequest\RequestExtractorInterfaceFactory;
-use Zend\Hydrator\Reflection;
+use Laminas\Hydrator\ReflectionHydrator;
 
 /**
  * Class RequestExtractor
@@ -78,7 +78,7 @@ class RequestExtractor implements RequestExtractorInterface
     private $shippingProducts;
 
     /**
-     * @var Reflection
+     * @var ReflectionHydrator
      */
     private $hydrator;
 
@@ -106,7 +106,7 @@ class RequestExtractor implements RequestExtractorInterface
         PackageInterfaceFactory $packageFactory,
         ModuleConfig $moduleConfig,
         ShippingProducts $shippingProducts,
-        Reflection $hydrator
+        ReflectionHydrator $hydrator
     ) {
         $this->shipmentRequest = $shipmentRequest;
         $this->requestExtractorFactory = $requestExtractorFactory;
```

**Comment by mam08ixo** [comment]
Thank you for bringing this to our attention. We will decide about appropriate measures once we have access to the upcoming Magento version.

**Comment by IbrahimS2** [comment]
@phoenix-bjoern What is confusing is this class specifically is an alias of ReflectionHydrator anyway, please refer to https://github.com/laminas/laminas-hydrator/blob/edb70c817b1c4a6724455f830ccc174757a94dd2/src/HydratorPluginManager.php#L69

**Comment by ngolatka** [comment]
_internal ref: DHLGW-1135_

**Comment by mam08ixo** [comment]
The current situation is that we can no longer support M2.3 and M2.4 with one module version. We therefore decided to do one more feature release for M2.3 and M2.4.2 before migrating all Zend requirements to their latest Laminas replacements. This will fix the issue but also drop support for Magento versions < 2.4.3

**Comment by mam08ixo** [comment]
We decided to drop the conflicting Zend dependency entirely. The latest module version as bundled with [DHL Shipping v2.1.0](https://github.com/netresearch/dhl-shipping-m2/releases/tag/2.1.0) therefore remains compatible with both, the M2.3 and M2.4 release line.
