### ISSUE TITLE
'Sperrgut'-remark not added to label if created via mass-action in sandbox mode

### ISSUE THREAD

**Issue by berwa** [netresearch/dhl-module-carrier-paket#5]
Hello Netresearch-team,
during the update to the latest version of this module we ran into an issue regarding the bulky-goods service:

**Preconditions:**
- Version 2.4.3 of Magento (Commerce)
- version 2.1.0 of dhl/shipping-m2 installed (resulting in version 2.2.0 of netresearch/dhl-module-carrier-paket)
- DHL Parcel Germany configurations: Use Bulky Goods Service - yes

**Steps to reproduce:**
- create label via mass-action from order-grid
- print label (e.g. via mass-action)
- check the content of the label

**Expected result:**
- resulting label contains a 'Sperrgut'-remark

**Actual result:**
- resulting label contains no 'Sperrgut'-remark

Thank you in advance and best regards

**Comment by mam08ixo** [comment]
I can confirm that, in sandbox mode, the label has no visual remark although the request XML does contain the selected service. In production mode everything works well for me. Can you confirm?

**Comment by berwa** [comment]
Hello @mam08ixo, 
Thank you very much for your reply and sorry I forgot to mention, that the previous tests were all done in sandbox-mode.

I also did some additional testing now and it seems like the problem is indeed sandbox-related:
2.2.0 of netresearch/dhl-module-carrier-paket - sandbox mode: remark is not present
2.2.0 of netresearch/dhl-module-carrier-paket - production mode: remark is present
2.0.1 of netresearch/dhl-module-carrier-paket - sandbox mode: remark is not present, but I'm pretty sure it was present a few months ago

Do you know if this topic was already drawn to the attention of somebody at DHL, or if we can do anything about it?

Thank you for your support and best regards

**Comment by ngolatka** [comment]
Since I handle 99% of the support cases that DHL escalates to us, I can at least tell you that nobody else has asked this particular question so far.

We know that the DHL APIs generally don't behave 100% identical in sandbox and production mode – which is annoying, but usually not a roadblock.

I think the subtext of @mam08ixo 's question is: is this really a problem for using the module productively?

**Comment by berwa** [comment]
Hello @ngolatka,
thank you for your reply.

No, there is no problem in using the module productively. 
It's just a 'developer convenience'-thing from the DHL API-side: as we modified the condition that determines if the remark is added to the label we want to make sure that customizing still works after updating the extension to latest version.

But that's not about the extension anymore; thank you for your nice and blazing fast support.

**Comment by mam08ixo** [comment]
I created a support request/issue report in the DHL developer portal.
