### ISSUE TITLE
LocationFinderServiceFactory uses ServiceFactory instead of ServiceFactoryInterface

### ISSUE THREAD

**Issue by template-provider** [netresearch/dhl-module-carrier-paket#6]
Hi,

I think this should be the ServiceFactoryInterface instead of the ServiceFactory? (+di.xml config)
https://github.com/netresearch/dhl-module-carrier-paket/blob/master/Model/Webservice/LocationFinderServiceFactory.php#L28

In every other module the implementation is with di.xml + ServiceFactoryInterface.
Problem for me is now, I want to override the ServiceFactory, but I cannot do this like the other implementations.

**Comment by mam08ixo** [comment]
I cannot recall why the two service factories in this directory were implemented differently. Maybe no reason at all.

You can still inject your custom `ServiceFactory` as long as it extends the original one.

**Comment by template-provider** [comment]
As a workaround I did that, but it would by nicer to just use the di.xml and one alternative implementation.
anyway ... thx

**Comment by mam08ixo** [comment]
But that's all it takes either way, no? The alternative factory implementation plus a little DI. Interface preference in one case, argument override in the other.

```xml
<type name="Dhl\Paket\Model\Webservice\LocationFinderServiceFactory">
    <arguments>
        <argument name="serviceFactory" xsi:type="object">My\Own\Factory</argument>
    </arguments>
</type>
```

**Comment by template-provider** [comment]
Thats what I did ... but my original aim, was to override the Dhl\Sdk\UnifiedLocationFinder\Service\ServiceFactory
In the other modules that was done with one entry, here I had to override the LocationFinderServiceFactory, too.
I actually don`t want to override the LocationFinderServiceFactory, but I need to ;-)

**Comment by template-provider** [comment]
A forget it .... saw what you mean.
It is possible that way ... but I did not extend the ServiceFactory, I used my own implementation from the ServiceFactoryInterface.
With the extends it will work .... but I want it totally clean ;-)

**Comment by mam08ixo** [comment]
Service factory injection was aligned in [version 2.4.0](https://github.com/netresearch/dhl-module-carrier-paket/releases/tag/2.4.0).
