### ISSUE TITLE
Electronic Export Notification

### ISSUE THREAD

**Issue by YiffyToys** [netresearch/dhl-module-carrier-paket#7]
The checkbox "Electronic Export Notification"
is described as "If enabled, DHL will automatically send a customs declaration electronically to the customs offices for dutiable shipments."

while in fact is sets a flag, that the user himself has to do that electronic export declaration and accompany the shipment with the respective document "Ausfuhrbegleitdokument".
While the user would assume that DHL would do that declaration given the entered content and the customer's customs reference and
the printed documents (that include a CN23) would be complete.
If the EAD is not included with the shipment, the shipment is returned by DHL.

Proposal:
* The checkbox should not be set by default
* The descriptive text of this checkbox should be updated to not be misleading
* if the checkbox is set, uppon creating postage for an export, the user should be reminded about his duty to do the electronic declaration and to attach the "Export Accompanying Document (EAD)"/"Ausfuhrbegleitdokument" (possibly with a [x] do not show again)

**Comment by mam08ixo** [comment]
You are absolutely right. Label and comment in the module configuration will be updated in the next release.

**Comment by mam08ixo** [comment]
Label and comment were updated in [version 2.4.0](https://github.com/netresearch/dhl-module-carrier-paket/releases/tag/2.4.0).

Thank you!
