### ISSUE TITLE
PHP Fatal Error at updating to 2.5.0

### ISSUE THREAD

**Issue by Alisinasyon** [netresearch/dhl-module-carrier-paket#8]
at  `bin/magento setup:upgrade`

i got the fowolling error:

`PHP Fatal error:  Class Dhl\Paket\Model\Webservice\ShipmentService contains 1 abstract method and must therefore be declared abstract or implement the remaining methods (Dhl\Sdk\Paket\Bcs\Api\ShipmentServiceInterface::validateShipments) in /pathToWeb/vendor/dhl/module-carrier-paket/Model/Webservice/ShipmentService.php on line 18`

Magento: 2.4.3
PHP: 7.4.28

**Comment by mam08ixo** [comment]
Hi @Alisinasyon, sorry for the inconvenience. Please roll back the `dhl/sdk-api-bcs` package until the next [dhl/shipping-m2](https://github.com/netresearch/dhl-shipping-m2) metapackage version is released with all dependencies properly declared. Thank you!

**Comment by Alisinasyon** [comment]
hi @mam08ixo, after Downgrade `dhl/sdk-api-bcs` to old (1.1.0) it is all fine. Thank you.

**Comment by Alisinasyon** [comment]
but at compile....

>setup:di:compile
Compilation was started.
Area configuration aggregation... 5/9 [===============>------------]  55% 56 secs 392.0 MiB
In ClassReader.php line 51:

>  Impossible to process constructor argument Parameter #2 [ <required> Netresearch\ShippingCore\Api\Util\LabelDataProviderInterface $labelDataProvider ] of Netresearch\ShippingUi\ViewModel\Rma\CustomerLabel class


>In ClassReader.php line 71:

>  Class Netresearch\ShippingCore\Api\Util\LabelDataProviderInterface does not exist


>setup:di:compile

**Comment by mam08ixo** [comment]
Same problem, but with a different package. Please downgrade `netresearch/module-shipping-core`. In general, avoid updating any of the `netresearch` or `dhl` packages on their own while the metapackage release is in progress.

**Comment by Alisinasyon** [comment]
Downgraded `netresearch/module-shipping-core` to previous (2.6.0). Have finished processes, and works. Thank you for help and quick reponse.

**Comment by mam08ixo** [comment]
Sorry again, we will let you know when the release is completed and it is safe to update.

**Comment by mam08ixo** [comment]
[Post & DHL Shipping version 2.5.0](https://github.com/netresearch/dhl-shipping-m2/releases/tag/2.5.0) is available on Marketplace and Packagist. All updated packages should now play nicely together.
