### ISSUE TITLE
Compatibility with Magento 2.4.4 monolog/monolog

### ISSUE THREAD

**Issue by in-session** [netresearch/dhl-module-carrier-paket#9]
Hello All, 

it seems that there is a problem with the monolog/monolog package when updating to Magento 2.4.4.

![Ashampoo_Snap_Mittwoch, 20  April 2022_8h3m15s](https://user-images.githubusercontent.com/16542619/164161783-50d66f6d-edf7-48c3-8e5c-9b0208b0f7ab.png)

The dependency should be adjusted:
`"monolog/monolog": "^1.25||^2.3",`

**Comment by in-session** [comment]
already a issues open: https://github.com/netresearch/dhl-shipping-m2/issues/44

**Comment by ngolatka** [comment]
Duplicate (sort of), closing this for now.
